Module4 task2
htmlacademy-javascript/517717-keksobooking-21 pull request #5
Opened 2020-10-20 18:34 UTC by Moroschka

2020-10-21 20:19 UTC, maraero commented on js/main.js
> +const getCardWork = function (index) {
Что значит это имя? :)

2020-10-21 20:19 UTC, maraero commented on js/main.js
> +const getCardWork = function (index) {
И я читаю и не понимаю, что тут происходит

2020-10-21 20:22 UTC, maraero commented on js/main.js
> +  const mapPins = similarListElement.querySelectorAll(`.map__pin[type="button"]`);
Зачем здесь дополнительно указывать [type=...]?

2020-10-21 20:23 UTC, maraero commented on js/main.js
> +    mapPins[i].addEventListener(`click`, function () {
Вам рассказывали о делегировании событий? Давай не будем вешать обработчик на каждый пин? Представь, что пинов было быы 100

2020-10-21 20:24 UTC, Moroschka commented on js/main.js
> +  const mapPins = similarListElement.querySelectorAll(`.map__pin[type="button"]`);
Чтобы не затронуть кнопку указателя mapPin Control

2020-10-21 20:25 UTC, maraero requested changes
Давай в первую очередь разберёмся с обработчиками событий для пинов? Делать нужно, конечно, через делегирование событий. Иначе при большом количестве пинов будет создаваться слишком много обработчиков. Подумай, как это можно сделать. Если что, можем созвониться и обсудить.

К валидации давай вернёмся чуть позже, когда закончим с предыдущим заданием, чтобы я не смотрел один и тот же код два раза

2020-11-02 20:57 UTC, maraero commented on js/main.js
> +  const mapCards = fieldMap.querySelectorAll(`.map__card`);
А карточек может быть больше одной? Если да, то почему?

2020-11-02 21:10 UTC, maraero commented on js/main.js
> +const getCardOfPin = function (evt) {
Я предлагаю тебе более простое решение. Давай каждому кликабельному элементу (пину) просто добавим уникальный id? Тогда можно будет проще идентифицировать и клик по нему, и чему он соответствует, и удалять его в дальнейшем

2020-11-02 21:11 UTC, maraero requested changes
Всё выглядит хорошо. Но давай сделаем проще?
Для пинов начнём использовать id.
И заодно подольём сюда мастер (который предварительно нужно обновить)

2020-11-05 17:53 UTC, maraero commented on js/main.js
> +    pin.setAttribute(`id`, i);
Я не уверен, что это хороший способ добавлять id.

Хороший способ -- добавить в каждый объект мок-объекта поле id, а затем использовать его сразу (!) при создании пинов (не добавлять постфактум). Тогда можно будет обойтись без сложного селектора, а проверять класс и наличие id

2020-11-06 13:40 UTC, maraero commented on js/main.js
> +        "id": `${index - 1}`
А почему index - 1? Индекс и так с 0 считается :)

2020-11-06 13:41 UTC, merged